swagger: "2.0"

info:
  title: API crudLight
  version: '1.0'

host: "localhost"

paths:
  /user:
    post:
      tags:
      - User
      operationId: create
      description: Creates a user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/User"
      responses:
        '201':
          description: Created
          schema:
            $ref: "#/definitions/User"
        '400':
          description: Bad request
        '500':
          description: Server error
          
  /user/{id}:
    parameters:
        - in: "path"
          name: "id"
          required: true
          type: integer
          format: int
    get:
      tags:
        - User
      operationId: get
      description: Returns a user by ID
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/User"
        '500':
          description: Server error
    patch:
      tags:
        - User
      operationId: update
      description: Updates a user by ID
      consumes:
        - aplication/json
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/User"
      responses:
        '200':
          description: OK
        '500':
          description: Server error
    delete:
      tags:
        - User
      operationId: delete
      description: Deletes user by ID
      responses:
        '200':
          description: OK
        '500':
          description: Server error
          
definitions:
  User:
    type: "object"
    properties:
      id: 
        type: integer
        format: "int"
      name:
        type: string
      birth_date:
        type: string
