// Code generated by go-swagger; DO NOT EDIT.

// Package restapi API crudLight
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0
//
//  Consumes:
//    - aplication/json
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
