// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateOKCode is the HTTP code returned for type UpdateOK
const UpdateOKCode int = 200

/*UpdateOK OK

swagger:response updateOK
*/
type UpdateOK struct {
}

// NewUpdateOK creates UpdateOK with default headers values
func NewUpdateOK() *UpdateOK {

	return &UpdateOK{}
}

// WriteResponse to the client
func (o *UpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateInternalServerErrorCode is the HTTP code returned for type UpdateInternalServerError
const UpdateInternalServerErrorCode int = 500

/*UpdateInternalServerError Server error

swagger:response updateInternalServerError
*/
type UpdateInternalServerError struct {
}

// NewUpdateInternalServerError creates UpdateInternalServerError with default headers values
func NewUpdateInternalServerError() *UpdateInternalServerError {

	return &UpdateInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
